### ISSUE TITLE
doc: Enable all features

### ISSUE THREAD

**Issue by chrysn** [RIOT-OS/rust-riot-wrappers#53]
So far, there has been one chip for which all major features were usable (nrf52840), and thus the riot-wrappers could be documented based on that one. With #36 (DAC), this is no longer the case.

How can we build documentation that covers all features without having such a chip?

**Comment by chrysn** [comment]
(This could also have been reported against https://gitlab.com/etonomy/riot-doc-helpers -- but a possible resolution is to replace that).

**Comment by Remmirad** [comment]
I am not quite sure I understand the problem, but I tried to setup a little RIOT module e.g. `generate` (target: `native`), added all needed modules to its Makefile (grep'ed them from `lib.rs`), and then setup this crates `.cargo/config.toml` with something like this here:
```toml
[env]
RIOT_COMPILE_COMMANDS_JSON = "generated/compile_commands.json"
RIOT_USEMODULE = "all modules as obtained from riot compile output"
[build]
target = "native target"
```
This way I then could use `cargo doc -F "features"` to build the documentation that seems to include all specified modules.
